

import java.awt.*;
import java.awt.geom.*;
import java.util.Random;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ha4176577
 */
public class DisplayPanel extends javax.swing.JPanel {
    int xPoints[]= new int[3];
    int yPoints[] = new int[3];
    int baseLength;
    int reps;
    /**
     * Creates new form DisplayPanel
     */
    public DisplayPanel() {
        initComponents();
        baseLength = 800;
        reps = 3;
  //      xPoints[0]= baseLength/2;
  //      xPoints[1]= 0;
  //      xPoints[2]=baseLength;
  //      yPoints[0]= 0;
  //      yPoints[1]=(int) Math.sqrt(3)*baseLength;
  //      yPoints[2]= (int) Math.sqrt(3)*baseLength;
    }
   

       private void paintLayer(Graphics2D g2,int numofLayers,int base,int x, int y){
           if(numofLayers!=0){
             g2.setColor(Color.black);
             g2.draw(new Polygon(new int[]{x,x -base/2, x + base/2},new int[]{ y , y + (int) Math.sqrt(3)*base,y + (int) Math.sqrt(3)*base} , 3));
          //   int[] set1x,set2x,set3x;
          //   set1x = new int[]{baseLength/2,200-base/4,200+base/4};   //{xPoints[0], xPoints[1]+(xPoints[2]-xPoints[1])/3 , xPoints[2]-(xPoints[2]-xPoints[1])/3};
          //   set2x = new int[]{xPoints[0]/2, xPoints[1], xPoints[2]/2};
           //  set3x = new int[]{xPoints[0]/2, xPoints[1]/2, xPoints[2]};
          //   int[] set1y,set2y,set3y;
          //   set1y = new int[]{yPoints[0], yPoints[1]/2, yPoints[2]/2};
           //  set2y = new int[]{yPoints[0]/2, yPoints[1], yPoints[2]/2};
           //  set3y = new int[]{yPoints[0]/2, yPoints[1]/2, yPoints[2]};
            
           //  paintLayer(g2, set1x,set1y,numofLayers-1,baseLength);
          //   paintLayer(g2, set2x,set2y,numofLayers-1);
           //  paintLayer(g2, set3x,set3y,numofLayers-1);
           paintLayer(g2,numofLayers-1,base/2,x,y);
           paintLayer(g2,numofLayers-1,base/2, x - base/4 ,y + (int) Math.sqrt(3)*base/2 );
           paintLayer(g2,numofLayers-1,base/2, x + base/4 ,y + (int) Math.sqrt(3)*base/2 ); 
         }
       }
        public void paintComponent(Graphics g){
        this.setSize(baseLength, baseLength); 
        Graphics2D g2= (Graphics2D)g;
        g2.setColor(Color.white);
        g2.fill(new Rectangle2D.Double(0, 0, baseLength, baseLength));
        Random r= new Random();
        //r.setSeed(100);
        paintLayer(g2, reps ,baseLength, baseLength/2 ,0);

    }      
       
    public void setReps(int i){
        reps = i;
        repaint();
    }
    
    public  class Animate implements Runnable{
    			public void run(){
				while(true){
					for(int i=0; i<11;i++){
						setReps(i);
						try{
								Thread.sleep(20);
						}catch(Exception e){
								System.out.println("it didnt work");
						}
					}
					for(int i=10; i>=0;i--){
						setReps(i);
						try{
								Thread.sleep(20);
						}catch(Exception e){
								System.out.println("it didnt work");
						}
					}				
			}
		}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                         
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                       


    // Variables declaration - do not modify                    
    // End of variables declaration                  
}